services:
  sftp:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
        - ./serve-folder:/home
        - ./conf/users.conf:/etc/sftp/users.conf:ro
    ports:
        - "8022:22"
    restart: always

  nginx:
    image: nginx
    container_name: nginx_server
    volumes:
      - ./serve-folder:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"
      - "8443:443"
    restart: unless-stopped
