services:
  sftp:
    image: atmoz/sftp
    volumes:
        - /media/upload:/home/user/upload
    ports:
        - "8022:22"
    command: user:password:1001

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"

