version: "1.0"
services:
  sftp:
    image: atmoz/sftp
    volumes:
        - /media/upload:/home/user/upload
    ports:
        - "8022:22"
    command: user:password:1001:100

  nginx:
    image: nginx
    container_name: nginx_server
    volumes:
      - ./serve-folder:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "8080:80"

